DROP CLASS chemical IF EXISTS
DROP CLASS molecule IF EXISTS
DROP CLASS reaction IF EXISTS
DROP CLASS spectator IF EXISTS
DROP CLASS source IF EXISTS

DROP CLASS productList IF EXISTS
DROP CLASS reactantList IF EXISTS